export const LANDING = '/'
export const HOME = '/home'
export const SIGN_UP = '/signup'
export const LOG_IN = '/login'
export const COLLECTION = '/login'
export const CREATE_RECIPE = '/create'
export const PASSWORD_FORGET = '/resetpw'